RainBlock/merkle-patricia-tree

package-lock.json, package.json, src/index.spec.ts, src/index.ts
This PR moves most tests in index.js (except for checkpointing ones) to spec.ts
Also, both the key and val are forced to be type buffer.
=> Migrate most tests in index.js to spec.ts

src/index.ts
This PR updates the documentation for `get()` to reflect the new witness API introduced in #3.
=> Update witness get docs

package.json
This patch fixes npm run compile to correctly copy the original js files to the build directory.
=> Fix npm run compile

src/index.ts, src/proof.spec.ts
This PR converts `VerifyWitness` to be a non-async function. 
Code using await should still work, but any code which expected `VerifyWitness`
to return a promise will have to be refactored.
=> Convert VerifyWitness to non-async

dist/trie.js, karma.conf.js, package-lock.json, package.json, src/official.spec.ts, tsconfig.json, webpack.config.js
Previously, the in-browser tests were using the original code. 
This PR updates browser code so it is generated using webpack instead.
The Karma configuration has been updated to run code generated from
webpack, and the runner/reporter have been updated to match the mocha
style now used in tests.
Currently, the webpack generated artifacts are quite large (~250KB).
This could be because of dependencies and potentially inline source maps.
Issue #18 has been opened to track this.
=> Fix browser tests; webpack switch

.gitmodules
It seems that a submodule to the official test repository used to
be used for tests.
This PR removes that submodule, since it seems to be undocumented,
and the test files are (for now) in the source tree.
=> Remove git modules

package.json, src/index.ts
Previously, docs were including methods from tests (*.spec.ts) as well as internal methods.
This PR removes all unexported methods from being included in the docs.
=> Remove unexported methods from docs

src/index.ts, src/proof.spec.ts
It seems that verify witness fails when there is an embedded extension branch. This causes an "Unexpected end of proof error".
This can occur if there are small values and keys.
A simple tree that causes this error can be created by executing:
put(a, a)
put(b, b)
put(c, c)
This PR fixes `VerifyWitness` to handle this case.
This seems to be a bug inherited from the upstream project and should be fixed there as well.
A PR has been opened under  ethereumjs/merkle-patricia-tree#51
=> Fix verifyWitness embedded extension-branch

package-lock.json, package.json, src/index.ts
This PR removes the original tree and fully moves to an in-memory tree using in-memory node objects. It currently passes all tests.
Performance is much better in some benchmarks, but in benchmarks where the root hash is calculated often, performance is significantly worse because no memoization is currently performed, and all nodes are rehashed (and re-serialized) each time.
Performance under this PR:
```
no-op: 203302±1.37% ops/s 0.005±0.0003 ms/op (61 runs)
put (empty tree): 148007±2.29% ops/s 0.007±0.0007 ms/op (79 runs)
get (empty tree): 123978±1.08% ops/s 0.008±0.0004 ms/op (82 runs)
generate 1k-1k-32-ran: 7.22±2.78% ops/s 138.479±12.2518 ms/op (39 runs)
generate 1k-1k-32-mir: 6.83±1.77% ops/s 146.483±8.0458 ms/op (37 runs)
generate 1k-9-32-ran: 0.17±0.70% ops/s 5745.930±32.2490 …
```
=> Use own nodes, remove original tree

src/index.bench.ts, src/index.spec.ts, src/index.ts, src/official.spec.ts, src/proof.spec.ts
This PR removes async from all the APIs, since there is no need to wait for disk writes anymore.
In addition, basic memoization is implemented which significantly speeds up the tree.
Compared to the original tree, performance is now at:
```
no-op: 202962±0.57% ops/s 0.005±0.0001 ms/op (78 runs)
put (empty tree): 166655±0.54% ops/s 0.006±0.0001 ms/op (77 runs)
get (empty tree): 132321±0.95% ops/s 0.008±0.0003 ms/op (79 runs)
generate 1k-10k-32-ran: 145±1.28% ops/s 6.908±0.3744 ms/op (69 runs)
generate 1k-1k-32-ran: 17.46±4.31% ops/s 57.265±8.7154 ms/op (48 runs)
generate 1k-1k-32-mir: 14.98±1.94% ops/s 66.776±5.5292 ms/op (70 runs)
generate 1k-9-32-ran: 1.32±2.24% ops/s 760.233±25.3012 ms/op (11 runs)
generate 1k-5-32-ran: 0.89±1.82% ops/s 1127.114±26.6204 ms/op (9 runs)
generate …
```
=> Switch to sync API, basic memoization

README.md
This PR corrects the URL for the travis shield to use the .com address.
=> Travis shield org->com

src/index.spec.ts, src/index.ts
This PR fixes issue #34, where a value was lost when an extension shrinks,
and adds proper tests.
=> Fix issue with extension shrink

src/index.spec.ts, src/index.ts
This PR fixes three issues with VerifyWitness, mostly dealing with the treatment of embedded nodes.
1) VerifyWitness returns error when value is inside an embeddedbranch (closes #37)
2) VerifyWitness returns error when embedded branch is inside embedded extension (closes #36)
3) VerifyWitness returns error when value is inside of a branch node followed by an extension
=> Fix issue with verify embedded-embedded

karma.conf.js, package-lock.json, package.json, src/index.ts
This PR addresses a bug where extension nodes that became empty were not pruned.
For example:
```
branch
branch
*extension <-- shrinks to ""
branch <-- old nibbles added here
```
It also adds a test with the full initial genesis state and ensures the correct root is calculated.
=> Fix extension not removed and add full genesis test

.travis.yml, README.md, package.json
This PR increases the speed of CI by switching to the Travis container-based infrastructure.
It also deprecates Node <10 support, since BigInts aren't supported, and we will move to BigInts soon.
In a month, Node 10 will become LTS anyway. 
Node >10 is now a required dependency.
=> Increase CI speed, deprecate node <10 support

package.json, src/index.spec.ts, src/index.ts
This PR adds a new typed interface which retains backwards compatibility with the untyped interface that expects Buffers.
At construction time, you can pass through key conversion and value conversion routines. If the routines are not provided, defaults which accept Buffers are used.
This PR is in preparation for a new internal change which will use bigints as the underlying type for keys, reducing the number of conversions needed to search and traverse the tree.
=> Add typed interface

package.json, src/index.ts
Instead of memoizing buffers, this PR changes the behavior of the memoization code to memoize bigints.
Unfortunately, this does result in a small trade-off as branch nodes and extension nodes will need to convert to Buffers in order to generate a hash the first time/when they are changed.
It does yield an overall small performance increase, however.
=> Memoize bigints when possible

src/index.ts
We introduce memoization for the rlpEncodings of serialized nodes.
Current benchmarks:
```
no-op: 192580±1.06% ops/s 0.005±0.0003 ms/op (82 runs)
put (empty tree): 155309±1.09% ops/s 0.006±0.0003 ms/op (79 runs)
get (empty tree): 165504±1.38% ops/s 0.006±0.0004 ms/op (81 runs)
individual bulk get: 42383±1.41% ops/s 0.024±0.0006 ms/op (17 runs)
individual get 1: 138877±9.43% ops/s 0.007±0.0013 ms/op (17 runs)
generate 1k-10k-32-ran: 691±2.33% ops/s 1.448±0.1520 ms/op (78 runs)
generate 1k-1k-32-ran: 66.64±1.88% ops/s 15.005±1.2702 ms/op (78 runs)
generate 1k-1k-32-mir: 55.44±4.08% ops/s 18.039±3.0722 ms/op (67 runs)
generate 1k-9-32-ran: 21.55±4.91% ops/s 46.396±8.5370 ms/op (54 runs)
generate 1k-5-32-ran: 18.47±7.96% ops/s 54.130±15.0786 ms/op (47 runs)
generate 1k-3-32-ran: 18.14±3.89% …
```
=> Memoizing rlp encoding of nodes

package.json, src/index.spec.ts, src/index.ts
This PR makes memoizing serializations optional, which improves performance when proof retrieval (and the RLP encoded nodes) is not required.
=> Add memoziation serializations as an option instead of required

package.json, src/index.spec.ts, src/index.ts, src/proof.spec.ts
This PR changes the behavior of get() so that nodes are not serialized when a witness is retrieved.
Instead, a new function, rlpSerializeWitness() must be called if you wish to obtain a serialized witness to be passed into verifyWitness.
Also, the API previously known as VerifyWitness has been renamed to verifyWitness to match code conventions.
=> Don't serialize nodes when get() is called

.gitignore, package-lock.json, package.json, src/index.ts
This PR updates typedoc to 0.14.2 for it to support bigint.
It fixes the build error.
As typedoc creates docs and coverage folders, adding them to .gitignore
=> Fixing build; removing docs and coverage

src/index.spec.ts, src/index.ts
From #52 Memoizing rlp-encoding of serialized nodes - We get a speedup of 56x in case of individual bulk gets and 12x in case of a single individual get.
So, batchGet and batchPut using radix-sort are no longer more performant than multiple individual gets and puts. For more detailed explanation read #68 
Benchmark results:
```
no-op: 235889±0.46% ops/s 0.004±0.0001 ms/op (69 runs)
put (empty tree): 184552±0.89% ops/s 0.005±0.0002 ms/op (83 runs)
get (empty tree): 197534±0.79% ops/s 0.005±0.0002 ms/op (84 runs)
generate 1k-10k-32-ran: 734±2.20% ops/s 1.362±0.1344 ms/op (77 runs)
generate 1k-1k-32-ran: 70.51±6.93% ops/s 14.183±4.5429 ms/op (82 runs)
generate 1k-1k-32-mir: 66.60±0.87% ops/s 15.016±0.5834 ms/op (76 runs)
generate 1k-9-32-ran: 20.79±1.37% ops/s 48.090±2.4477 ms/op (53 runs) …
```
=> Batch using loops

src/index.spec.ts, src/index.ts
Efficient batchCOW by eliminating redundant node copies.
Nodes that have to be copied are marked for all the keys in the batch and are copied once at the end. The keys from the copied nodes are then modified.
Bottom line: 
Takes almost the same amount of the time as the batchCOW implementation in master, but reduces the total amount of heap required for performing the copy on write insert.
15K keys on an initially empty-tree:
```
batch insert on empty: 4.38±4.51% ops/s 228.305±25.4993 ms/op (26 runs)
batchCOW on empty: 4.39±1.37% ops/s 228.024±7.7195 ms/op (26 runs)
```
This PR
```
batchSize : 15K
batch insert into empty: 4.35±3.49% ops/s 230.126±19.8758 ms/op (26 runs)
batchCOW from prev: 2.10±2.09% ops/s 476.091±17.9618 ms/op (15 runs)
batchSize : 150K
batch insert: 0.38±1.65% ops/s …
```
=> Efficient batchCOW

src/index.ts
This PR fixes `tree.del()` operation.
If we perform a `tree.root` query in between multiple `tree.del()` operations, the root hash of the tree differs from the expected value. The memoized hashes are not cleared in a corner case, while performing deletes. This PR clears the node hashes.
`Case:`
Consider deleting from the path [..., branch_node, target_node]. After deleting the target_node if branch_node has only one branch remaining, a connecting node is used to collapse the branch and the branch_node. The memoized hash of the connecting node is not cleared. This results in the root hash mismatch.
`TestCase to reproduce the bug:`
Insert a `tree.root` in any of the `secure trieTests` in `src/official.spec.ts` while performing inserts and deletes to observe that the root hashes mismatch.
=> :Bug: Fixing del operation

package-lock.json, package.json, src/index.ts
This PR fixes two dependencies not listed in the package.json:
The dependency on `benchmark` is removed. For some reason this was being imported in `index.ts`.
The dependency on `ethereumjs-util` is added. This is needed for legacy node decoding, it seems.
=> Fix missing packages

package.json, src/index.spec.ts, src/index.ts
This PR adds a new test which checks if we are able to read a value from a cached merkle tree that was pruned. 
In the test, the merkle tree currently returns null. It should throw an error, as there is insufficient information to determine whether or not the key exists or not.
See issue #88
=> Pruned tree doesn't throw error test

package.json, src/index.spec.ts, src/index.ts
This PR adds functionality as requested in #89.
This PR adds support for node cache in CachedMerklePatriciaTree.
When a key's value is read from the CachedMerklePatriciaTree and bag of nodes,
- the value of the key and 
- a list of nodes read from the bag of nodes
are returned. Upon further thought; the API suggested in #89  made so much more sense than the attempt at #90. See #90 for the discussion
This PR closes #89
=> nodeBag cache

package-lock.json, package.json, src/index.spec.ts, src/index.ts
This PR adds a new call to insert key value pairs into the `CachedMerklePatriciaTree`.
```  
putWithNodeBag(
key: K, value: V, staleNodes: Set<bigint>|undefined,
...nodeBag: Array<Map<bigint, MerklePatriciaTreeNode<V>>>)
```
putWithNodeBag takes the key, value pair to insert, a set to populate the nodes in the nodeBag that become stale and a nodeBag which is a cache of MerklePatriciaTreeNodes
=> putWthNodeBag to insert into CachedMerklePatriciaTree

package-lock.json, package.json, src/index.ts
This PR updates the MerklePatriciaTreeNode hash function to accommodate for HashNodes
=> Update merkle node hash computation

src/index.ts
This PR fixes the errors thrown by _getRecursive in CachedMerklePatriciaTree. It should only throw two types of errors: MerkleKeyNotFoundError and MerkleNodePrunedError
=> Fix errors thrown

package.json, src/index.spec.ts, src/index.ts
This PR adds two new API calls to MerklePatriciaTree and CachedMerklePatriciaTree:
nodeCount and size.
nodeCount recursively traverses the tree and counts the number of nodes present in the it.
size returns the length of the concatenation of rlp encodings of all the nodes in the tree.
=> Node count and tree size
